-- ════════════════════════════════════════════════════════════════════════
-- dashboard_analysis 테이블 삭제 — 죽은 테이블 정리
--
-- 배경: 2026-08-12(20260812_dashboard_holdings.sql)에 대시보드 "오늘의 AI분석"
-- (포트폴리오 전체) 섹션용으로 dashboard_holdings와 함께 생성됐다. 2026-09-01
-- (commit 789000c)에 그 섹션이 포트폴리오분석 메뉴와 내용이 완전 중복돼 통째로
-- 삭제됐고, 이 테이블을 유일하게 썼던 app/api/dashboard/analysis/route.ts도
-- 같이 삭제됐다 — 당시 커밋 메시지에 "dashboard_analysis 테이블은 그대로 둠
-- (삭제는 별도 판단 필요, DB 변경 아님)"라고 명시적으로 남겨둔 후속 작업이다.
--
-- 안전 확인(2026-09-03): 코드베이스 전체에서 dashboard_analysis를 참조하는
-- 실행 코드가 전혀 없음을 grep으로 재확인했다 — app/api/dashboard/analysis
-- 라우트 자체가 존재하지 않고, .from('dashboard_analysis') 호출도 0건이며
-- (같은 "대시보드" 계열의 dashboard_holdings만 4개 라우트에서 계속 쓰이는 중),
-- vercel.json에도 관련 크론/함수 설정이 없다. 남은 참조는 원본 생성 마이그레이션
-- (역사 기록이라 보존)과 .e2e-tmp의 예전 조사용 스크립트(배포되지 않는 스크래치
-- 파일)뿐이었다.
--
-- dashboard_holdings는 이 마이그레이션과 무관 — 계속 쓰이므로 그대로 둔다.
-- ════════════════════════════════════════════════════════════════════════

drop table if exists public.dashboard_analysis;
